/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Curso;
import Clases.Estudiante;
import Clases.Materia;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class frmEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form frmEstudiante
     */
    public frmEstudiante() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarEstudiante = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnCrearE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        spnNe = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtNm = new javax.swing.JTextField();
        btnAgregarE = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtMateria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtN1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtN2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtN3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCodMat = new javax.swing.JTextField();
        btnBuscarMat = new javax.swing.JButton();
        btnAgregarMateria = new javax.swing.JButton();
        btnActualizarN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lstDatos = new java.awt.List();
        btnPrueba = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lstLibreta = new java.awt.List();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso y Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        txtCedula.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel1.setText("Cedula:");

        btnBuscarEstudiante.setBackground(new java.awt.Color(0, 153, 153));
        btnBuscarEstudiante.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnBuscarEstudiante.setForeground(new java.awt.Color(0, 153, 153));
        btnBuscarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/buscar.jpg"))); // NOI18N
        btnBuscarEstudiante.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudianteActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel11.setText("Nro Estudiantes");

        btnCrearE.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnCrearE.setText("Crear");
        btnCrearE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setText("Nombres:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setText("Apellidos:");

        btnActualizar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar Datos");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel9.setText("Nro. Materias");

        btnAgregarE.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnAgregarE.setText("Grabar Estudiante");
        btnAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)
                        .addComponent(spnNe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearE, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtNm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar)
                        .addGap(27, 27, 27)
                        .addComponent(btnAgregarE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(btnCrearE)
                        .addComponent(jLabel9)
                        .addComponent(txtNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spnNe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar)
                    .addComponent(btnAgregarE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Asignatura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel4.setText("Materia:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel6.setText("Nota 1");
        jLabel6.setToolTipText("");

        txtN1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel7.setText("Nota 2");

        txtN2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel8.setText("Nota 3");

        txtN3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel10.setText("Codigo Materia");

        txtCodMat.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        btnBuscarMat.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnBuscarMat.setText("Buscar Materia");
        btnBuscarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMatActionPerformed(evt);
            }
        });

        btnAgregarMateria.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnAgregarMateria.setText("Guardar Materia");
        btnAgregarMateria.setEnabled(false);
        btnAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMateriaActionPerformed(evt);
            }
        });

        btnActualizarN.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnActualizarN.setText("Actualizar Notas");
        btnActualizarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMateria))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtN3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnActualizarN)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnAgregarMateria)))))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodMat, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarMat)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMat))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtN3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarMateria)
                        .addComponent(btnActualizarN))
                    .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Libreta de calificaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        lstDatos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lstDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstDatosActionPerformed(evt);
            }
        });

        btnPrueba.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnPrueba.setText("Datos prueba");
        btnPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaActionPerformed(evt);
            }
        });

        btnimprimir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPrueba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnimprimir)
                        .addContainerGap(125, Short.MAX_VALUE))
                    .addComponent(lstDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lstDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrueba)
                    .addComponent(btnimprimir))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Libreta Individual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lstLibreta, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lstLibreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("SISTEMA ACADEMICO");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Denise Villarreal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Curso objCur ;
    int pos;

    private void btnPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaActionPerformed
        // TODO add your handling code here:
int nEstud=20;
 objCur= new Curso("1ro",nEstud);
        Materia m1 = new Materia("M01", "FISICA", 5.0, 8.5, 3.9);
        Materia m2 = new Materia("M02", "INGLES", 9.0, 9.5, 7.9);
        Materia m3 = new Materia("M03", "QUIMICA", 8.0, 9.3, 5.0);

        Estudiante e1 = new Estudiante("1002003001", "BENITO", "SUAREZ", 3);
        e1.agregarMateria(m1);
        e1.agregarMateria(m2);
        e1.agregarMateria(m3);
        objCur.agregarEstudiante(e1);

//        lstDatos.add("" + objCur.vecE[0].getCedula());
//        lstDatos.add("" + objCur.vecE[0].getNombres() + ", " + objCur.vecE[0].getApellidos());
//        lstDatos.add("" + objCur.vecE[0].vecM[0].imprimir());
//        lstDatos.add("" + objCur.vecE[0].vecM[1].imprimir());
//        lstDatos.add("" + objCur.vecE[0].vecM[2].imprimir());
//        lstDatos.add("----------------------------------------------------------");

        Materia m4 = new Materia("M04", "MATEMATICAS", 4.0, 4.5, 7.9);
        Materia m5 = new Materia("M05", "LITERATURA", 7.0, 7.5, 7.9);
        Materia m6 = new Materia("M06", "PROGRAMACION", 8.0, 2.3, 5.0);
        Estudiante e2 = new Estudiante("1001112223", "ANA", "FRANK", 3);
        e2.agregarMateria(m4);
        e2.agregarMateria(m5);
        e2.agregarMateria(m6);
        objCur.agregarEstudiante(e2);
//        lstDatos.add("" + objCur.vecE[1].getCedula());
//        lstDatos.add("" + objCur.vecE[1].getNombres() + ", " + objCur.vecE[1].getApellidos());
//        lstDatos.add("" + objCur.vecE[1].vecM[0].imprimir());
//        lstDatos.add("" + objCur.vecE[1].vecM[1].imprimir());
//        lstDatos.add("" + objCur.vecE[1].vecM[2].imprimir());
//        lstDatos.add("----------------------------------------------------------");

        Materia m7 = new Materia("M07", "INGLES", 7.1, 6.5, 3.4);
        Materia m8 = new Materia("M08", "BASE", 7.1, 6.5, 3.4);

        Estudiante e3 = new Estudiante("1002223334", "CATALINA", "FLORES", 2);
        e3.agregarMateria(m7);
        e3.agregarMateria(m8);

        objCur.agregarEstudiante(e3);
//        lstDatos.add("" + objCur.vecE[2].getCedula());
//        lstDatos.add("" + objCur.vecE[2].getNombres() + ", " + objCur.vecE[2].getApellidos());
//        for (int i = 0; i < 2; i++) {
//            lstDatos.add("" + objCur.vecE[2].vecM[i].imprimir());
//        }
//        lstDatos.add("----------------------------------------------------------");

        Materia m10 = new Materia("M10", "EXPRESION ORAL", 8.0, 8.0, 8.0);
        Materia m11 = new Materia("M11", "MANUALIDADES", 3.0, 4.8, 7.0);
        Materia m12 = new Materia("M12", "EDUCACION FISICA", 6.0, 6.8, 7.0);
        Materia m13 = new Materia("M13", "HISTORIA", 7.0, 7.0, 7.0);
        Materia m14 = new Materia("M14", "CIENCIAS N", 6.0, 8.0, 5.0);
        Materia m15 = new Materia("M15", "SOCIALES", 6.0, 9.0, 7.0);
        Estudiante e4 = new Estudiante("1004005007", "MANUELA", "MUÑOZ", 6);
        e4.agregarMateria(m10);
        e4.agregarMateria(m11);
        e4.agregarMateria(m12);
        e4.agregarMateria(m13);
        e4.agregarMateria(m14);
        e4.agregarMateria(m15);
        objCur.agregarEstudiante(e4);
//        lstDatos.add("" + objCur.vecE[3].getCedula());
//        lstDatos.add("" + objCur.vecE[3].getNombres() + " " + objCur.vecE[3].getApellidos());
//        for (int i = 0; i < 6; i++) {
//            lstDatos.add("" + objCur.vecE[3].vecM[i].imprimir());
//        }
//        lstDatos.add("------------------------------------------------------------------------------");
        Materia m16 = new Materia("M16", "FRANCES", 9.0, 7.0, 6.0);
        Estudiante e5 = new Estudiante("1005557779", "RODRIGO", "ALARCON", 1);
        e5.agregarMateria(m10);

        objCur.agregarEstudiante(e5);
//        lstDatos.add("" + objCur.vecE[4].getCedula());
//        lstDatos.add("" + objCur.vecE[4].getNombres() + " " + objCur.vecE[4].getApellidos());
//        for (int i = 0; i < 1; i++) {
//            lstDatos.add("" + objCur.vecE[4].vecM[i].imprimir());
//        }
//        lstDatos.add("------------------------------------------------------------------------------");
        Materia m17 = new Materia("M17", "RELIGION", 8.0, 8.0, 8.0);
        Materia m18 = new Materia("M18", "QUIMICA", 3.0, 4.8, 7.0);
        Materia m19 = new Materia("M19", "ANATOMIA", 6.0, 6.8, 7.0);
        Materia m20 = new Materia("M20", "BIOLOGIA", 7.0, 7.0, 7.0);

        Estudiante e6 = new Estudiante("1006007008", "CARLITA", "POZO", 4);
        e6.agregarMateria(m17);
        e6.agregarMateria(m18);
        e6.agregarMateria(m19);
        e6.agregarMateria(m20);

        objCur.agregarEstudiante(e6);
//        lstDatos.add("" + objCur.vecE[5].getCedula());
//        lstDatos.add("" + objCur.vecE[5].getNombres() + " " + objCur.vecE[5].getApellidos());
//        for (int i = 0; i < 4; i++) {
//            lstDatos.add("" + objCur.vecE[5].vecM[i].imprimir());
//        }
//        lstDatos.add("------------------------------------------------------------------------------");

      imprimirTodos();
    }//GEN-LAST:event_btnPruebaActionPerformed

    public void imprimirlibreta(int posE) {
        lstLibreta.removeAll();
        for (int i = 0; i < objCur.vecE[posE].getTamM(); i++) {
            lstLibreta.add("" + objCur.vecE[posE].vecM[i].imprimir());
        }
    }

    private void txtN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN3ActionPerformed
    Estudiante objEstu;
    int n;
   

    private void btnBuscarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMatActionPerformed
        
        String codMate= txtCodMat.getText();
        int posMa = objCur.buscarmat(pos, codMate);
        if (posMa >= 0) {
            txtMateria.setText(objCur.vecE[pos].vecM[posMa].getNombreMat());
            txtN1.setText("" + objCur.vecE[pos].vecM[posMa].getN1());
            txtN2.setText("" + objCur.vecE[pos].vecM[posMa].getN2());
            txtN3.setText("" + objCur.vecE[pos].vecM[posMa].getN3());
        }
            
        else{
            JOptionPane.showMessageDialog(null, "Codigo de materia NO existe");
        }    
    }//GEN-LAST:event_btnBuscarMatActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        objCur.eliminarPersona(pos);
        mostrarDatos();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        String cedula, nombres, apellidos;
        cedula = txtCedula.getText();
        nombres = txtNombre.getText();
        apellidos = txtApellidos.getText();

        objCur.vecE[pos].setCedula(cedula);
        objCur.vecE[pos].setNombres(nombres);
        objCur.vecE[pos].setApellidos(apellidos);

        mostrarDatos();

        JOptionPane.showMessageDialog(this, "La  modificacion se realizo con exito");

    }//GEN-LAST:event_btnActualizarActionPerformed
   Materia objMate;
    private void btnAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMateriaActionPerformed
       
        
        int posE = objCur.tamE - 1;
        int nMates =objCur.vecE[posE].nmaterias;
        String codMate = txtCodMat.getText();
        String nomMate = txtMateria.getText();
        double n1 = Double.parseDouble(txtN1.getText());
        double n2 = Double.parseDouble(txtN2.getText());
        double n3 = Double.parseDouble(txtN3.getText());
        Materia mate = new Materia(codMate, nomMate, n1, n2, n3);
        objCur.vecE[posE].agregarMateria(mate);
        limpiarMateria();
        if (objCur.vecE[posE].tamM>= nMates) {
            btnAgregarMateria.setEnabled(false);
        }
         JOptionPane.showMessageDialog(this, "MATERIA AGREGADA IMPRIMA");
         limpiar();
            

 
    }//GEN-LAST:event_btnAgregarMateriaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCrearEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEActionPerformed
        // TODO add your handling code here:
         n = Integer.parseInt(spnNe.getValue().toString());
        
         objCur = new Curso("1ro", n);
     
        
        JOptionPane.showMessageDialog(this, "Nro de Estudiantes Creado");
        btnCrearE.setEnabled(false);
        
    }//GEN-LAST:event_btnCrearEActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        String cedBuscar = txtCedula.getText();

        pos = objCur.buscarPersona(cedBuscar);
        if (pos >= 0) {
            txtNombre.setText(objCur.vecE[pos].getNombres());
            txtApellidos.setText(objCur.vecE[pos].getApellidos());

            imprimirlibreta(pos);
            lstLibreta.add("" + pos);
            btnBorrar.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, "Cédula de estudiante NO existe");
        }
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed

    private void lstDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstDatosActionPerformed

    private void btnAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEActionPerformed
    
//           
//         try {
//        String ced = txtCedula.getText();
//        String nom = txtNombre.getText();
//        String apell = txtApellidos.getText();
//        int nM = Integer.parseInt(txtNm.getText());
//        
//
//        Estudiante objEstudiante = new Estudiante(ced, nom, apell, nM);
//        objCur.agregarEstudiante(objEstudiante);
//        
//         JOptionPane.showMessageDialog(this, "ESTUDIANTE AGREGADO");
//         limpiar();
//          
//        } catch (ArrayIndexOutOfBoundsException excepcion) {
//            JOptionPane.showMessageDialog(this, "ARREGLO LLENO");
//        } catch (NumberFormatException excepcion) {
//            JOptionPane.showMessageDialog(this, "Verifique los datos algo esta mal");
//        } catch (NullPointerException e) {
//            JOptionPane.showMessageDialog(this, "El ARREGLO AUN NO ESTA CREADO");
//        }
  try{
  int nmates = Integer.parseInt(txtNm.getText());
        String ced = txtCedula.getText();
        String nom = txtNombre.getText();
        String apell=txtApellidos.getText();
        Estudiante estud=new Estudiante(ced, nom, apell, nmates);
        objCur.agregarEstudiante(estud);
        btnAgregarMateria.setEnabled(true);
        JOptionPane.showMessageDialog(this, "ESTUDIANTE AGREGADO");
        limpiar();
        
  } catch(ArrayIndexOutOfBoundsException excepcion){
     JOptionPane.showMessageDialog(this, "ARREGLO LLENO");  
     txtCedula.setEnabled(false);
     txtNombre.setEnabled(false);
     txtApellidos.setEnabled(false);
  }catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(this, "Falta llenar los campos");
             txtNm.setBackground(Color.pink);
             
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "El ARREGLO AUN NO ESTA CREADO");
        }
        
         
    }//GEN-LAST:event_btnAgregarEActionPerformed
    
    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        imprimirTodos();
       
     
    }//GEN-LAST:event_btnimprimirActionPerformed
int posM;
    private void btnActualizarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarNActionPerformed
         double n1 = Double.parseDouble(txtN1.getText());
        double n2 = Double.parseDouble(txtN2.getText());
        double n3 = Double.parseDouble(txtN3.getText());
       
        
        String cedBuscar = txtCedula.getText();
        int posEncotrada = objCur.buscarPersona(cedBuscar);
        
        
        
        objCur.vecE[posEncotrada].vecM[posM].setN1(n1);
        objCur.vecE[posEncotrada].vecM[posM].setN2(n2);
        objCur.vecE[posEncotrada].vecM[posM].setN3(n3);
       
       mostrarDatos();
        
    }//GEN-LAST:event_btnActualizarNActionPerformed
 
    
    public void limpiar() {
        txtCedula.setText(null);
        txtNombre.setText("");
        txtApellidos.setText(null);
        txtMateria.setText(null);
        txtN1.setText(null);
        txtN2.setText(null);
        txtN3.setText(null);

    }
       public void limpiarMateria() {
        txtCodMat.setText(null);
        txtMateria.setText(null);
        txtN1.setText(null);
        txtN2.setText(null);
        txtN3.setText(null);
        txtCodMat.requestFocus();
       }
       
    public void mostrarDatos() {
        lstDatos.removeAll();
        for (int i = 0; i < objCur.getTamE(); i++) {
            lstDatos.add("" + objCur.vecE[i].getCedula());
            lstDatos.add("" + objCur.vecE[i].getNombres() + " " + objCur.vecE[i].getApellidos());
          
       for (int j = 0; j < objCur.vecE[i].tamM; j++) {
            
            lstDatos.add(""+objCur.vecE[i].vecM[j].imprimir());
        }
        lstDatos.add("----------------------------------------------------------");
        }

    }
    
    public void imprimirTodos() {
        lstDatos.removeAll();
        for (int i = 0; i < objCur.tamE; i++) {
            lstDatos.add("CEDULA=" + objCur.vecE[i].getCedula());
            lstDatos.add("NOMBRES=" + objCur.vecE[i].getNombres());
            lstDatos.add( "APELLIDOS="+objCur.vecE[i].getApellidos());                  
            for (int j = 0; j < objCur.vecE[i].tamM; j++) {
                lstDatos.add(objCur.vecE[i].vecM[j].imprimir());
            }
            lstDatos.add("----------------------------------------------------------");
        }
    }

    public void imprimirIndividual(int pos) {
        lstDatos.removeAll();
          lstDatos.add("CEDULA=" + objCur.vecE[pos].getCedula());
        lstDatos.add("ESTUDIANTE=" + objCur.vecE[pos].getNombres());
        lstDatos.add("APELLIDOS="+objCur.vecE[pos].getApellidos());
        
        for (int j = 0; j < objCur.vecE[pos].tamM; j++) {
            
            lstDatos.add(""+objCur.vecE[pos].vecM[j].imprimir());
        }
       lstDatos.add("..........................................");
    }

     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarN;
    private javax.swing.JButton btnAgregarE;
    private javax.swing.JButton btnAgregarMateria;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnBuscarMat;
    private javax.swing.JButton btnCrearE;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrueba;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private java.awt.List lstDatos;
    private java.awt.List lstLibreta;
    private javax.swing.JSpinner spnNe;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodMat;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtN3;
    private javax.swing.JTextField txtNm;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
