/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLASES;

import DIBUJOS.dibujo;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class frmplanilla extends javax.swing.JFrame {

    /**
     * Creates new form frmplanilla
     */
    public frmplanilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        label3 = new java.awt.Label();
        jLabel10 = new javax.swing.JLabel();
        lblnacimiento = new javax.swing.JLabel();
        lblfechanacimiento = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbledad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblimprimir = new javax.swing.JTable();
        lblsigno = new javax.swing.JLabel();
        jpnimagen4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsueldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spnhijos = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        cmbxestadocivil = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        rbtnhombre = new javax.swing.JRadioButton();
        rbtnmujer = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnimprimir = new javax.swing.JButton();
        btnprocesar = new javax.swing.JButton();
        btnuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(255, 255, 204));

        label3.setText("label3");

        lblnacimiento.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lblnacimiento.setText("FechaNacimiento");

        lblfechanacimiento.setBackground(new java.awt.Color(255, 255, 153));
        lblfechanacimiento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblfechanacimiento.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel9.setText("Su edad es");

        lbledad.setBackground(new java.awt.Color(255, 255, 153));
        lbledad.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbledad.setOpaque(true);

        tblimprimir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Email", "Hijos", "Sueldo", "Estado Civil", "Genero"
            }
        ));
        jScrollPane1.setViewportView(tblimprimir);

        lblsigno.setText("SIGNO");

        jpnimagen4.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jpnimagen4Layout = new javax.swing.GroupLayout(jpnimagen4);
        jpnimagen4.setLayout(jpnimagen4Layout);
        jpnimagen4Layout.setHorizontalGroup(
            jpnimagen4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        jpnimagen4Layout.setVerticalGroup(
            jpnimagen4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRES");

        txtnombres.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtnombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombresFocusLost(evt);
            }
        });
        txtnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresActionPerformed(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        jLabel2.setText("APELLIDOS");

        txtapellido.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });

        jLabel3.setText("CEDULA");

        txtcedula.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedulaFocusLost(evt);
            }
        });
        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });

        jLabel4.setText("EMAIL");

        txtemail.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel6.setText("SUELDO");

        txtsueldo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtsueldo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsueldoFocusLost(evt);
            }
        });
        txtsueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsueldoActionPerformed(evt);
            }
        });
        txtsueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsueldoKeyTyped(evt);
            }
        });

        jLabel5.setText("NROHIJOS");

        jLabel8.setText("ESTADO CIVIL");

        cmbxestadocivil.setBackground(new java.awt.Color(204, 204, 255));
        cmbxestadocivil.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        cmbxestadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTERO", "CASADO", "DIVORCIADO", "VIUDO" }));

        jLabel7.setText("FECHA NAC");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("genero"));

        rbtnhombre.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rbtnhombre);
        rbtnhombre.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        rbtnhombre.setText("HOMBRE");
        rbtnhombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnhombreActionPerformed(evt);
            }
        });

        rbtnmujer.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rbtnmujer);
        rbtnmujer.setText("MUJER");
        rbtnmujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnmujerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rbtnhombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(rbtnmujer)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnhombre)
                    .addComponent(rbtnmujer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnhijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spnhijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbxestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnimprimir.setBackground(new java.awt.Color(255, 204, 204));
        btnimprimir.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnimprimir.setForeground(new java.awt.Color(102, 102, 102));
        btnimprimir.setText("IMPRIMIR");
        btnimprimir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        btnprocesar.setBackground(new java.awt.Color(255, 204, 204));
        btnprocesar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnprocesar.setForeground(new java.awt.Color(102, 102, 102));
        btnprocesar.setText("PROCESAR");
        btnprocesar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnprocesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocesarActionPerformed(evt);
            }
        });

        btnuevo.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnuevo.setForeground(new java.awt.Color(153, 153, 153));
        btnuevo.setText("NUEVO");
        btnuevo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 153)));
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprocesar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprocesar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(lblnacimiento)
                                            .addComponent(lbledad, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblfechanacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(lblsigno))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jpnimagen4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lbledad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnacimiento))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblsigno)
                        .addGap(18, 18, 18)
                        .addComponent(jpnimagen4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String fecha;
  public Arreglo arrayr = new Arreglo(20);
    public int tam = 0;
    public int año;
    public int mes, dia;


    Validaciones op2 = new Validaciones();
     dibujo obj = new dibujo();
    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
  char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingrese solo Letras");
            evt.consume();

        }        
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
 char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingrese solo Letras");
            evt.consume();

        }       
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
      char caracter = evt.getKeyChar();
        int limite = 10;
        //verificacion  numeros
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /* BACK_SPACE*/)) {
         
            evt.consume();  // ignorar el evento de teclado
        }
        
        // limite de datos
        if (txtcedula.getText().length() == limite) {
         
            evt.consume();

        }
    }//GEN-LAST:event_txtcedulaKeyTyped
 public String A() {
        String R = " ";
        if (rbtnhombre.isSelected()) {
            R = "Masculino";
        }
        if (rbtnmujer.isSelected()) {
            R = "Femenino";
        }

        return R;
    }
    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
    Empleado  e = new Empleado(Integer.parseInt(txtcedula.getText()), txtnombres.getText(), txtapellido.getText(),txtemail.getText(),Integer.parseInt(spnhijos.getValue().toString()), Double.parseDouble(txtsueldo.getText()), cmbxestadocivil.getSelectedItem().toString(), A());
        JOptionPane.showMessageDialog(this, e);

          
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void rbtnhombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnhombreActionPerformed
  

    }//GEN-LAST:event_rbtnhombreActionPerformed

    private void rbtnmujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmujerActionPerformed

    }//GEN-LAST:event_rbtnmujerActionPerformed

    private void btnprocesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocesarActionPerformed
       arrayr.addElemento(new Empleado(Integer.parseInt(txtcedula.getText()), txtnombres.getText(), txtapellido.getText(),txtemail.getText(),Integer.parseInt(spnhijos.getValue().toString()), Double.parseDouble(txtsueldo.getText()), cmbxestadocivil.getSelectedItem().toString(), A()));

      
        Object[] fila = new Object[]{Integer.parseInt(txtcedula.getText()), txtnombres.getText(), txtapellido.getText(),txtemail.getText(),Integer.parseInt(spnhijos.getValue().toString()), Double.parseDouble(txtsueldo.getText()), cmbxestadocivil.getSelectedItem().toString(), A()};
        DefaultTableModel dtm = (DefaultTableModel) tblimprimir.getModel();
        dtm.addRow(fila);
        //imprimir la fecha
        //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        Date edad = jdate.getDate();
        int año = jdate.getCalendar().get(Calendar.YEAR);
        int mes = jdate.getCalendar().get(Calendar.MONTH) + 1;
        int dia = jdate.getCalendar().get(Calendar.DAY_OF_MONTH);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        lbledad.setText(" EDAD: " + formato.format(edad));
        LocalDate nacimiento = LocalDate.of(año, mes, dia);
        LocalDate ahora = LocalDate.now();
        Period periodo = Period.between(nacimiento, ahora);
        String formatoss = "EEEE d' de 'MMMM' de 'yyyy";
        SimpleDateFormat sdf = new SimpleDateFormat(formatoss);
        fecha = "EDAD: " + "Años: "
                + periodo.getYears() + " " + "Meses: " + periodo.getMonths() + " " + "Dias: " + periodo.getDays() + " ";
        lblfechanacimiento.setText("Fecha Nacimiento: " + sdf.format(edad));
        lbledad.setText("EDAD: " + "Años: "
           
                + periodo.getYears() + " " + "Meses: " + periodo.getMonths() + " " + "Dias: " + periodo.getDays() + " ");
        /*
        if (dia == 31 && (mes == 1 || mes == 5 || mes == 7 || mes == 8 || mes == 10 || mes == 12 || mes == 3)) {
            lbldiaAnterior.setText("Dia Anterior:" + (dia - 1) + " " + (mes - 1) + " " + año);
            lbldiaSiguiente.setText("Dia Siguiente: 1 " + " " + mes + " " + año);

        } else if (dia == 30 && (mes == 4 || mes == 6 || mes == 9 || mes == 11)) {
            lbldiaAnterior.setText("Dia Anterior:" + (dia - 1) + " " + (mes - 1) + " " + año);
            lbldiaSiguiente.setText("Dia Siguiente: 1 ");

        } else if (dia == 1 && (mes == 2 || mes == 4 || mes == 6 || mes == 8 || mes == 9 || mes == 11)) {
            lbldiaAnterior.setText("Dia Anterior: 31");
            lbldiaSiguiente.setText("Dia Siguiente:" + (dia + 1) + " " + mes + " " + año);

        } else if (dia == 1 && mes == 1) {
            lbldiaAnterior.setText("Feliz Año Nuevo  " + "  Dia anterior: 31 " + "-" + ("Diciembre") + "-" + (año - 1));
            lbldiaSiguiente.setText("Feliz Año Nuevo  " + "  Dia Siguiente: " + (dia + 1) + " " + mes + " " + año);
        } else if (dia > 1 && dia < 31 || dia > 1 && dia < 30) {
            lbldiaAnterior.setText("Dia Anterior: " + (dia - 1) + " " + mes + " " + año);
            lbldiaSiguiente.setText("Dia Siguiente:" + (dia + 1) + " " + mes + " " + año);
        }*/
        switch (mes) {

            case 1:
                if (dia > 21) {
                    lblsigno.setText("Signo Zodiacal: ACUARIO ");
                    obj.acuario(jpnimagen4.getGraphics());

                } else {
                    lblsigno.setText("Signo Zodiacal: CAPRICORNIO ");
                    obj.capricornio(jpnimagen4.getGraphics());
                }
                break;
            case 2:
                if (dia > 19) {
                    lblsigno.setText("Signo Zodiacal:  PISCIS ");
                    obj.piscis(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal: ACUARIO ");
                    obj.acuario(jpnimagen4.getGraphics());
                }
                break;
            case 3:
                if (dia > 20) {
                    lblsigno.setText("Signo Zodiacal: ARIES ");
                    obj.aries(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal: PISCIS ");
                    obj.piscis(jpnimagen4.getGraphics());
                }
                break;
            case 4:
                if (dia > 20) {
                    lblsigno.setText("Signo Zodiacal: TAURO ");
                    obj.tauro(jpnimagen4.getGraphics());

                } else {
                    lblsigno.setText("Signo Zodiacal: ARIES ");
                    obj.aries(jpnimagen4.getGraphics());
                }
                break;
            case 5:
                if (dia > 21) {
                    lblsigno.setText("Signo Zodiacal: GEMINIS ");
                    obj.geminis(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal: TAURO ");
                    obj.tauro(jpnimagen4.getGraphics());
                }
                break;
            case 6:
                if (dia > 20) {
                    lblsigno.setText("Signo Zodiacal: CANCER ");
                    obj.cancer(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal: GEMINIS ");
                    obj.geminis(jpnimagen4.getGraphics());
                }
                break;
            case 7:
                if (dia > 22) {
                    lblsigno.setText("Signo Zodiacal: LEO ");
                    obj.leo(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal: CANCER ");
                    obj.cancer(jpnimagen4.getGraphics());
                }
                break;
            case 8:
                if (dia > 21) {
                    lblsigno.setText("Signo Zodiacal: VIRGO ");
                    obj.virgo(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal: LEO ");
                    obj.leo(jpnimagen4.getGraphics());
                }
                break;
            case 9:
                if (dia > 22) {
                    lblsigno.setText("Signo Zodiacal: LIBRA ");
                    obj.libra(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal: VIRGO ");
                    obj.virgo(jpnimagen4.getGraphics());
                }
                break;
            case 10:
                if (dia > 22) {
                    lblsigno.setText("Signo Zodiacal: ESCORPIO ");
                    obj.escorpio(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal: LIBRA ");
                    obj.libra(jpnimagen4.getGraphics());
                }
                break;
            case 11:
                if (dia > 21) {
                    lblsigno.setText("Signo Zodiacal:SAGITARIO ");
                    obj.sagitario(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal:ESCORPIO ");
                    obj.escorpio(jpnimagen4.getGraphics());
                }
                break;
            case 12:
                if (dia > 21) {
                    lblsigno.setText("Signo Zodiacal: CAPRICORNIO ");
                    obj.capricornio(jpnimagen4.getGraphics());
                } else {
                    lblsigno.setText("Signo Zodiacal: SAGITARIO ");
                    obj.sagitario(jpnimagen4.getGraphics());
                }
                break;

        }         
    }//GEN-LAST:event_btnprocesarActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
Pattern patern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[_A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        String email = txtemail.getText();
        Matcher mather = patern.matcher(email);
        if (mather.find() == true) {
            JOptionPane.showMessageDialog(null, "El Email Ingresado Es Valido");
            txtemail.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "El email no es correcto " + "\n intente de nuevo");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtsueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsueldoActionPerformed

    private void txtsueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsueldoKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9') && (c < ',' || c > '.')) {
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
            evt.consume(); 
        }
    }//GEN-LAST:event_txtsueldoKeyTyped

    private void txtnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresActionPerformed
        
     
    
    }//GEN-LAST:event_txtnombresActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
       
        txtcedula.setText(" ");
        txtnombres.setText(" ");
        txtapellido.setText(" ");
        spnhijos.setToolTipText(" ");
        txtsueldo.setText(" ");
        txtemail.setText(" ");
        jdate.setToolTipText(" ");
        lbledad.setText("Edad:");
        lblnacimiento.setText("Nacimiento:");
        
        txtemail.setEnabled(true);
        txtcedula.setEnabled(true);
    }//GEN-LAST:event_btnuevoActionPerformed

    private void txtcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaFocusLost
String cedula = txtcedula.getText();

        if (op2.valida(cedula) == true) {
            txtcedula.setBackground(Color.WHITE);
            txtcedula.setEnabled(false);

        } else {
            txtcedula.setBackground(Color.pink);
            txtcedula.setEnabled(true);
        }       
    }//GEN-LAST:event_txtcedulaFocusLost

    private void txtnombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombresFocusLost
 String nombres = txtnombres.getText();

        if (op2.valida(nombres) == true) {
            txtnombres.setBackground(Color.WHITE);
            txtnombres.setEnabled(false);

        } else {
            txtnombres.setBackground(Color.pink);
            txtnombres.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_txtnombresFocusLost

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
 String email = txtemail.getText();

        if (op2.valida(email) == true) {
            txtemail.setBackground(Color.WHITE);
            txtemail.setEnabled(false);

        } else {
            txtemail.setBackground(Color.pink);
            txtemail.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailFocusLost

    private void txtsueldoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsueldoFocusLost
 String cedula = txtsueldo.getText();

        if (op2.valida(cedula) == true) {
            txtsueldo.setBackground(Color.WHITE);
            txtsueldo.setEnabled(false);

        } else {
            txtsueldo.setBackground(Color.pink);
            txtsueldo.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsueldoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmplanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmplanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmplanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmplanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmplanilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnprocesar;
    private javax.swing.JButton btnuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbxestadocivil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JPanel jpnimagen4;
    private java.awt.Label label3;
    private javax.swing.JLabel lbledad;
    private javax.swing.JLabel lblfechanacimiento;
    private javax.swing.JLabel lblnacimiento;
    private javax.swing.JLabel lblsigno;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton rbtnhombre;
    private javax.swing.JRadioButton rbtnmujer;
    private javax.swing.JSpinner spnhijos;
    private javax.swing.JTable tblimprimir;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtsueldo;
    // End of variables declaration//GEN-END:variables

   
}
