/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class frmAsientos extends javax.swing.JFrame {
    int x = 15;
    int y = 10;
    int tamX = 0;
    int tamY = 0;
    static final int TableroX = 600;
    static final int TableroY = 600;
    
   JButton[][]Botones;
   Avion objAvion;
   Pasajero objP;
    
//    double costo=100;
    
    
    
    
    public frmAsientos() {
        initComponents();
        objAvion= new Avion(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAsiento = new javax.swing.JLabel();
        list1 = new java.awt.List();
        pnlAsientos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Pasajeros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel1.setText("Cedula:");

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setText("Nombres:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setText("Nacionalidad:");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel4.setText("Seleccione el destino:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel5.setText("Telefono:");

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnBuscar.setText("Buscar");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Prueba");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Asientos");

        lblValor.setBackground(new java.awt.Color(153, 255, 153));
        lblValor.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        lblValor.setText("0");

        jLabel7.setText("Valor");

        lblAsiento.setBackground(new java.awt.Color(153, 255, 153));
        lblAsiento.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        lblAsiento.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(txtDestino))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombres)
                                .addComponent(txtNacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)))
                        .addGap(27, 27, 27)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAsientosLayout = new javax.swing.GroupLayout(pnlAsientos);
        pnlAsientos.setLayout(pnlAsientosLayout);
        pnlAsientosLayout.setHorizontalGroup(
            pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        pnlAsientosLayout.setVerticalGroup(
            pnlAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(pnlAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void calcularDimension(int cantX, int cantY) {
        tamX = TableroX / cantX;
        tamY = TableroY / cantY;
    }
     private void RedibujarTablero() {
        //Se valida los componentes del elemento pnlTablero
       pnlAsientos.validate();
        
        //Se redibuja el elemento pnlTablero y sus componentes hijos
        pnlAsientos.repaint();
    }
      private void Click(JButton btn) {
 int asiento=JOptionPane.showConfirmDialog(null, "Realmente Deseas Este Asiento ", "Verificar Asiento", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (asiento==JOptionPane.YES_OPTION) {
        
            btn.setEnabled(false);
            lblAsiento.setText(""+btn.getText());
//            lblCosto.setText(""+(precio+50));
           
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione Su Asiento ");
        }
        
        
        
        
       // JOptionPane.showMessageDialog(this, "Soy el boton en la posición: " + btn.getToolTipText());
    }
       public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        return formato.format(fecha);

    }
double preciofinal=0;
/////
public void limpiar(){
    txtCodigo.setText("");
    txtNombre.setText("");
    txtApellido.setText("");
    lblAsiento.setText("0");
    
} 
    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         lblFecha.setText(fechaactual());
        lblfechaf.setText(fechaactual());
//Se settea el tamaño de la matriz de botones
        MatrizBotones = new JButton[DimensionX][DimensionY];
        //Se settea el tamaño de gridLayout de nuestro panel del tablero
        pnlAsientos.setLayout(new GridLayout(DimensionX, DimensionY));
        //Se obtiene el tamaño de los botones acorde a su cantidad
        ObtenerTamanioObjetos(DimensionX, DimensionY);
        //Se declaran los contadores a utilizar
        int contadorX, contadorY;
        //Se recorre la dimension X desde 0 hasta DimensionX
        for (contadorX = 0; contadorX < DimensionX; contadorX++) {

            //Se recorre la dimension Y desde 0 hasta DimensionY
            for (contadorY = 0; contadorY < DimensionY; contadorY++) {
                
//                if (contadorX>=0&&contadorX<5) {
//                    precio=precio+30;
//                    lblCosto.setText(""+precio);
////                } if (contadorX>5&&contadorX<=10) {
////                    preciofinal=precio+20;
////                    lblCosto.setText(""+preciofinal);
////                } if (contadorX>10&&contadorX<=15) {
////                    preciofinal=precio+20;
////                    lblCosto.setText(""+preciofinal);
////                }
                
                
               
                
                //Se crea un nuevo objeto de tipo JButton

                JButton btnNuevo = new JButton();
                //Se le asignan sus dimensiones (ancho, alto)
                btnNuevo.setSize(TamX, TamY);
                //Se asigna un texto con la posición del botón en la matriz al botón, al tooltip del botón
                btnNuevo.setToolTipText(Integer.toString(contadorX) + "/" + Integer.toString(contadorY));
             
            
                
              btnNuevo.setText(Integer.toString(contadorX+1) +"/"+ Integer.toString(contadorY+1) );
                btnNuevo.setBackground(Color.BLUE);
 

                //Se agrega a la matriz el botón recien creado
                MatrizBotones[contadorX][contadorY] = btnNuevo;
                //Se agrega un nuevo evento que maneje la acción clic sobre el botón creado
                MatrizBotones[contadorX][contadorY].addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        Click(btnNuevo);
                    }
                });
                //Se agrega al panel 
                pnlAsientos.add(MatrizBotones[contadorX][contadorY]);
                //Se redibuja el panel
                RedibujarTablero();
            }//Fin For - Y
        }//Fin For - X
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ltspasajeros.removeAll();
        for (int i = 0; i < objar.getTam(); i++) {
          ltspasajeros.add(""+objar.getVec()[i].getVuelo());
            ltspasajeros.add(""+objar.getVec()[i].getNombrep());
            ltspasajeros.add(""+objar.getVec()[i].getApellido());
            ltspasajeros.add(""+objar.getVec()[i].getAsiento());
            ltspasajeros.add(""+objar.getVec()[i].getOrigen());
            ltspasajeros.add(""+objar.getVec()[i].getDestino());
            ltspasajeros.add(""+objar.getVec()[i].getFecha());
            ltspasajeros.add(""+objar.getVec()[i].getCategoria());
            ltspasajeros.add(""+objar.getVec()[i].getPreciob());     
            
        
            ltspasajeros.add("___________________________");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
//         int vuelo = Integer.parseInt(txtCodigo.getText());
//
//        String origen = cmbOrigen.getSelectedItem().toString(),
//                destino = cmbDestino.getSelectedItem().toString(),
//                nombrep = txtNombre.getText(),
//                apellido = txtApellido.getText(),
//                fecha = lblfechaf.getText(),
//                aereolinea = cmbAer.getSelectedItem().toString(),
//                asiento = lblAsiento.getText(),
//                categoria = lblcategoria.getText();
//        double precio = Double.parseDouble(lblCosto.getText());
//        JOptionPane.showMessageDialog(null, "El Aereopuerto ofrece un Servicio de Tienda");
//        int confirmacion = JOptionPane.showConfirmDialog(null, "Antes de Confirmar Desea Comprar Algo Adicional ", "Verificar compra", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//        if (confirmacion == JOptionPane.YES_OPTION) {
//            JOptionPane.showMessageDialog(null, "Nos Vemos en la Tienda ");
//
//        } else {
//            objp = new pasajeros(vuelo, asiento, origen, destino, nombrep, apellido, fecha, aereolinea, categoria, precio);
//            objar.agregarCuenta(objp);
//            JOptionPane.showMessageDialog(null, "Has Comprado un Boleto");
//            limpiar();
//
//        } 
        
        
        
        
        
        
        int vuelo = Integer.parseInt(txtCodigo.getText());
                
        String origen = cmbOrigen.getSelectedItem().toString(),
                destino = cmbDestino.getSelectedItem().toString(),
                nombrep = txtNombre.getText(),
                apellido=txtApellido.getText(),
        fecha=lblfechaf.getText(),
                aereolinea=cmbAer.getSelectedItem().toString(),
                asiento=lblAsiento.getText();
                
                
        

        objp = new pasajeros(vuelo, asiento, origen, destino, nombrep, apellido, fecha, aereolinea, "ejecutivo", 35.14);
        objar.agregarCuenta(objp);
        limpiar();
    }                                           

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       objar = new aereopuerto(3);
        pasajeros objp1 = new pasajeros(005, "17", "ibarra", "quito", "antony", "vaca", "17/12/2019", "Tame", "economica", 38.50);
        objar.agregarCuenta(objp1);
        pasajeros objp2 = new pasajeros(007, "22", "quito", "guayaquil", "Jorje", "vaca", "17/12/2019", "vuelafacil", "premium", 50.0);
        objar.agregarCuenta(objp2);
        pasajeros objp3 = new pasajeros(7, "39", "guayaquil", "ibarra", "Edison", "vaca", "17/12/2019", "siemprevuela", "pro", 80.0);
        objar.agregarCuenta(objp3);
        System.out.println("exito");
        for (int i = 0; i < objar.getTam(); i++) {
            ltspasajeros.add(""+objar.getVec()[i].getNombrep());
//            lista1.addItem(""+objar.getVec()[i].getNombrep());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAsientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAsientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAsiento;
    private javax.swing.JLabel lblValor;
    private java.awt.List list1;
    private javax.swing.JPanel pnlAsientos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
