/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JOptionPane;
import clases.libreria;
import clases.libro;

/**
 *
 * @author hp
 */
public class frmlibros extends javax.swing.JFrame {

    /**
     * Creates new form frmlibros
     */
    public frmlibros() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btninsertar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnordenar = new javax.swing.JButton();
        txttitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtautor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txteditorial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcopias = new javax.swing.JTextField();
        btnordenar1 = new javax.swing.JButton();
        lstlibro = new java.awt.List();
        jLabel9 = new javax.swing.JLabel();
        txtanioedicion = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        txtMateria = new javax.swing.JTextField();
        txtnumlibros = new javax.swing.JTextField();
        btncrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 11))); // NOI18N

        btninsertar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btninsertar.setText("Insertar");
        btninsertar.setEnabled(false);
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setText("Codigo libro");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel4.setText("Titulo");

        btnordenar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnordenar.setText("ordenar");
        btnordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenarActionPerformed(evt);
            }
        });

        txttitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttituloActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel5.setText("Autor");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel6.setText("Añoedicion");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel7.setText("Materia");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel8.setText("Nro copias");

        btnordenar1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnordenar1.setText("dta prueba");
        btnordenar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenar1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel9.setText("Editorial");

        btnbuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnbuscar.setText("buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnborrar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btnborrar.setText("Borrar");
        btnborrar.setEnabled(false);
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txttitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtautor)
                                .addComponent(txteditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtanioedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtcopias, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btninsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnordenar1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbuscar)
                        .addComponent(btnordenar1)
                        .addComponent(btnordenar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txteditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtanioedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtcopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btninsertar)
                            .addComponent(btnActualizar)
                            .addComponent(btnborrar)))
                    .addComponent(lstlibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btncrear.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btncrear.setText("crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setText("Ingresar el numero de libros");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/biblioteca.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnumlibros, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncrear)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnumlibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncrear))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    libreria objlibreria;
    libro objlibro;
    private void txttituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttituloActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        // TODO add your handling code here:
        int nlibros = Integer.parseInt(txtnumlibros.getText());
        
        objlibreria = new libreria(nlibros);
        btncrear.setEnabled(false);
        btninsertar.setEnabled(true);
    }//GEN-LAST:event_btncrearActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed

        int cod = Integer.parseInt(txtCodigo.getText());
        String tit = txttitulo.getText();
        String autor = txtautor.getText();
        String edi = txteditorial.getText();
        String mat = txtMateria.getText();
        String anio = txtanioedicion.getText();

        int numcopi = Integer.parseInt(txtcopias.getText());
        
        objlibro = new libro(cod, autor, tit, edi, anio, mat, numcopi);
        objlibreria.agregalibro(objlibro);
        limpiar();
        mostrarDatos1();
        JOptionPane.showMessageDialog(this, "Libro ingresado con Exito..!!");
    }//GEN-LAST:event_btninsertarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        int conta = 0;
        btnActualizar.setEnabled(false);
        int id = Integer.parseInt(txtCodigo.getText());
        pos=objlibreria.buscarlibro(id);
        if(pos>=0){
            txttitulo.setText(objlibreria.vecLib[pos].getTitulo());
            txtautor.setText(objlibreria.vecLib[pos].getAutor());
            txteditorial.setText(objlibreria.vecLib[pos].getEditorial());
            txtanioedicion.setText(objlibreria.vecLib[pos].getAnioedi());
            txtMateria.setText(objlibreria.vecLib[pos].getMateria());
            txtcopias.setText(String.valueOf(objlibreria.vecLib[pos].getNrocopias()));
            btnActualizar.setEnabled(true);
            btnborrar.setEnabled(true);
        }
        else {
            btninsertar.setEnabled(false);
            btnActualizar.setEnabled(false);
            btnborrar.setEnabled(false);            
            JOptionPane.showMessageDialog(null, "Libro no encontrado ");
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenarActionPerformed
        // TODO add your handling code here:
        objlibreria.ordSelCopias();
        mostrarDatos1();

    }//GEN-LAST:event_btnordenarActionPerformed

    private void btnordenar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenar1ActionPerformed
        // TODO add your handling code here:
        Pruebadatos();
        mostrarDatos1();
    }//GEN-LAST:event_btnordenar1ActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
         objlibreria.eliminarLibro(pos);
        mostrarDatos1();
      
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String titulo, autor, editorial, materia, anioE;
        int copias;

        copias = Integer.parseInt(txtcopias.getText());
        titulo = txttitulo.getText();
        autor = txtautor.getText();
        editorial = txteditorial.getText();
        materia = txtMateria.getText();
        anioE = txtanioedicion.getText();

        objlibreria.vecLib[pos].setTitulo(titulo);
        objlibreria.vecLib[pos].setAutor(autor);
        objlibreria.vecLib[pos].setEditorial(editorial);
        objlibreria.vecLib[pos].setMateria(materia);
        objlibreria.vecLib[pos].setAnioedi(anioE);
        objlibreria.vecLib[pos].setNrocopias(copias);
        mostrarDatos1();

        JOptionPane.showMessageDialog(this, "La  modificacion se realizo con exito");


    }//GEN-LAST:event_btnActualizarActionPerformed
//pos=posicion
    int pos = 0;

    public void limpiar() {
        txtCodigo.setText(null);
        txttitulo.setText("");
        txtautor.setText(null);
        txteditorial.setText(null);
        txtanioedicion.setText(null);
        txtcopias.setText(null);
         txtMateria.setText(null);
        lstlibro.removeAll();
 
    }

    public void mostrarDatos1() {
        lstlibro.removeAll();

        for (int i = 0; i < objlibreria.getTam(); i++) {

            lstlibro.add("codigo:" + objlibreria.vecLib[i].getCodigo());
            lstlibro.add("Nombre:" + objlibreria.vecLib[i].getTitulo());
            lstlibro.add("Autor:" + objlibreria.vecLib[i].getAutor());
            lstlibro.add("Editorial:" + objlibreria.vecLib[i].getEditorial());
            lstlibro.add("Anioedicion:" + objlibreria.vecLib[i].getAnioedi());
            lstlibro.add("Materia:" + objlibreria.vecLib[i].getMateria());
            lstlibro.add("Numero de copias:" + objlibreria.vecLib[i].getNrocopias());
            lstlibro.add("************************************");

        }

    }



    public void Pruebadatos() {
        objlibreria = new libreria(10);
        int cod = 1701;
        String autor = "Charles perrault";
        String tit = "La cenicienta";
        String edi = "Alemania";
        String anioedi="2006";
        String mat = "PROGRAMACION";
        int numcopi = 4;
        objlibro = new libro(cod, autor, tit, edi, anioedi, mat, numcopi);
        objlibreria.agregalibro(objlibro);
        
        
        int cod2 = 1702;
        String autor2 = "carlos cautemoc sanchez";        
        String tit2 = "los ojos de mi princesa";
        String edi2 = "Londres";
        String anioedi2="2006";        
        String mat2 = "MATEMATICA";
        int numcopi2 = 6;
        libro objlib2 = new libro(cod2, autor2, tit2, edi2, anioedi2, mat2, numcopi2);
        objlibreria.agregalibro(objlib2);
        
        
        int cod3 = 1703;
        String autor3 = "Juan Gallegos Lara";        
        String tit3 = "El lobo estepario";
        String edi3 = "Venecia";
        String anioedi3="2003";               
        String mat3 = "FISICA";
        int numcopi3 = 1;
        libro objlib3 = new libro(cod3, autor3, tit3, edi3, anioedi3, mat3, numcopi3);
        objlibreria.agregalibro(objlib3);
        
        
        int cod4 = 1704;
        String autor4 = "Louide L";        
        String tit4 = "El poder esta dentro de ti";
        String edi4 = "Manhatan";
        String anioedi4="2008";                    
        String mat4 = "Motivacional";
        int numcopi4 = 3;
        libro objlib4 = new libro(cod4, autor4, tit4, edi4, anioedi4, mat4, numcopi4);
        objlibreria.agregalibro(objlib4);
         
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmlibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmlibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmlibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmlibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmlibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton btnordenar;
    private javax.swing.JButton btnordenar1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private java.awt.List lstlibro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtanioedicion;
    private javax.swing.JTextField txtautor;
    private javax.swing.JTextField txtcopias;
    private javax.swing.JTextField txteditorial;
    private javax.swing.JTextField txtnumlibros;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
