/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import clases.vector;
import clases.nota;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class frmAlumno extends javax.swing.JFrame {

    /**
     * Creates new form frmAlumno
     */
    public frmAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtn1 = new javax.swing.JTextField();
        txtn2 = new javax.swing.JTextField();
        txtn3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtAsignatura = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cboestado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnPrueba = new javax.swing.JButton();
        lstDatos = new java.awt.List();
        btnordenar = new javax.swing.JButton();
        btnin = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        lblaprobados = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 11))); // NOI18N

        jLabel1.setText("CEDULA");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("APELLIDO");

        jLabel4.setText("NOTA 1");

        jLabel5.setText("NOTA 2");

        jLabel6.setText("NOTA 3");

        jLabel7.setText("ASIGNATURA");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnactualizar.setText("actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        jLabel8.setText("ESTADO");

        cboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APROBADO", "PENDIENTE", "SUPLETORIO", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(194, 194, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtAsignatura)
                    .addComponent(txtApellido)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnactualizar)
                            .addComponent(btnBorrar))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IMPRIMIR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 11))); // NOI18N

        btnPrueba.setText("Prueba");
        btnPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaActionPerformed(evt);
            }
        });

        lstDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstDatosActionPerformed(evt);
            }
        });

        btnordenar.setText("ordenar");
        btnordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenarActionPerformed(evt);
            }
        });

        btnin.setText("insertar");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });

        btnEstado.setText("Estado");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        lblaprobados.setBackground(new java.awt.Color(255, 204, 204));
        lblaprobados.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEstado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnordenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblaprobados, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lstDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lstDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnin)
                    .addComponent(btnordenar)
                    .addComponent(btnPrueba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstado)
                .addGap(26, 26, 26)
                .addComponent(lblaprobados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel9.setText("SISTEMA ACADEMICO ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   vector objVec;
    nota objper;

    int n = 10;
    int pos;
    
    public void mostrarDatos() {
        int i;
        
         lstDatos.removeAll();
         
        for (i = 0; i < objVec.tam; i++) {
            
            lstDatos.add(objVec.vec[i].imprimir());
        }

    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cedBuscar = txtCedula.getText();
                
        pos = objVec.buscarPersona(cedBuscar);
        if (pos >= 0) {
            txtNombre.setText(objVec.vec[pos].getNombres());
            txtApellido.setText(objVec.vec[pos].getApellidos());
            txtAsignatura.setText(objVec.vec[pos].getAsignatura());
            txtn1.setText(String.valueOf(objVec.vec[pos].getN1()));
            txtn2.setText(String.valueOf(objVec.vec[pos].getN2()));
            txtn3.setText(String.valueOf(objVec.vec[pos].getN3()));
            

            btnBorrar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Cédula de estudiante NO existe");
                 
    }//GEN-LAST:event_btnBuscarActionPerformed
    }
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        objVec.eliminarPersona(pos);
        mostrarDatos();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        String cedula, nombres,apellidos,asignatura;
        int n1,n2,n3;
       

        cedula = txtCedula.getText();
        nombres = txtNombre.getText();
        apellidos = txtApellido.getText();
        asignatura = txtAsignatura.getText();
        n1= Integer.parseInt(txtn1.getText());
        n2= Integer.parseInt(txtn2.getText());
        n3= Integer.parseInt(txtn3.getText());

        objVec.vec[pos].setCedula(cedula);
        objVec.vec[pos].setApellidos(apellidos);
        objVec.vec[pos].setNombres(nombres);
        objVec.vec[pos].setAsignatura(asignatura);
        objVec.vec[pos].setN1(n1);
        objVec.vec[pos].setN2(n2);
         objVec.vec[pos].getN3();


        mostrarDatos();

        JOptionPane.showMessageDialog(this, "La  modificacion se realizo con exito");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        // TODO add your handling code here:

        String ced =txtCedula.getText();
        String nombres = txtNombre.getText();
        String apellidos = txtApellido.getText();
        String asignatura = txtAsignatura.getText();
       
        int n1 = Integer.parseInt(txtn1.getText());
      int n2 = Integer.parseInt(txtn2.getText());
      int n3 = Integer.parseInt(txtn3.getText());
        nota objper=new nota(ced, nombres, apellidos, asignatura, n1, n2, n3);
        objVec.agregar(objper);

        limpiar();
        mostrarDatos();
        JOptionPane.showMessageDialog(this, "Estudiante ingresado con exito..!!");
    }//GEN-LAST:event_btninActionPerformed

    private void btnPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaActionPerformed
        objVec = new vector(n);
        nota p1 = new nota("100", "JUAN","ANDRADE ","PROGRAMACION",7, 8,5);
        objVec.agregar(p1);
        nota p2 = new nota("200", "ERIKA", "ANDRADE", "MATEMATICAS", 6, 5, 4);
        objVec.agregar(p2);
        nota p3 = new nota("300", "CARLOS", "GONZALES", "BASE DE DATOS", 9, 5, 10);
        objVec.agregar(p3);
        nota p4 = new nota("400", "MARIA", "ZAPATA", "INGLES", 6, 9, 10);
        objVec.agregar(p4);
        nota p5 = new nota("500", "LUIS", "MERA", "PROGRAMACION", 5, 10, 7);
        objVec.agregar(p5);
        nota p6 = new nota("600", "ANA", "CHULDE", "PROGRAMACION", 8, 10, 3);
        objVec.agregar(p6);
        nota p7 = new nota("700", "SOFIA", "AMARO", "PROGRAMACION", 8, 10, 3);
        objVec.agregar(p7);
        nota p8 = new nota("800", "CARLA", "C", "PROGRAMACION", 8, 10, 3);
        objVec.agregar(p8);
        nota p9 = new nota("900", "DENIS", "GARCIA", "PROGRAMACION", 8, 10, 3);
        objVec.agregar(p9);
        nota p10 = new nota("111", "DANIEL", "MEJIA", "INGLES", 8, 10, 3);
        objVec.agregar(p10);



        btnin.setEnabled(true);
        mostrarDatos();
    }//GEN-LAST:event_btnPruebaActionPerformed

    private void btnordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenarActionPerformed
lstDatos.removeAll();

        for (int i = 0; i <   objVec.getTam(); i++) {
 int prom=0;
int suma=0;
 int n1=objVec.getVec()[i].getN1();
 int n2=objVec.getVec()[i].getN2();
 int n3=objVec.getVec()[i].getN3();
 prom=((n1+n2+n3)/3);
 suma= n1+n2+n3;
          lstDatos.add("Cedula : " + objVec.getVec()[i].getCedula());
           lstDatos.add("Nombre : " + objVec.getVec()[i].getNombres());
           lstDatos.add("Apellidos : " + objVec.getVec()[i].getApellidos());
            lstDatos.add("Asignatura: " + objVec.getVec()[i].getAsignatura());
            lstDatos.add("Nota 1 : " + objVec.getVec()[i].getN1());
           lstDatos.add("Nota 2 : " +objVec.getVec()[i].getN2());
            lstDatos.add("Nota 3 : " +objVec.getVec()[i].getN3());
            lstDatos.add("Suma : "+suma);
            lstDatos.add("Promedio : "+prom);
             if (suma >21){
            lstDatos.add("Aprobado");
             }
             if (suma >=16&&prom<21){
            lstDatos.add("Supletorio");
             }
             if (suma <16){
            lstDatos.add("Perdido");
             }
             
         lstDatos.add("___________________________");
 
 
        }      
    }//GEN-LAST:event_btnordenarActionPerformed

    private void lstDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstDatosActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
         int conta=0;
        for (int i = 0; i < objVec.getTam(); i++) {
            if (objVec.vec[i].getSuma()>=21) {
                lstDatos.add("Nombre: "+ objVec.vec[i].getNombres());
                lstDatos.add("Materia: "+ objVec.vec[i].getAsignatura());
                lstDatos.add("Promedio: "+ objVec.vec[i].getSuma());
                lstDatos.add("APROBADO");
                lstDatos.add("*******************************************");
                conta ++;
                lblaprobados.setText("Aprobados ="+conta);
            }else
                if (objVec.vec[i].getSuma()>=16) {
                lstDatos.add("Nombre: "+ objVec.vec[i].getNombres());
                lstDatos.add("Materia: "+ objVec.vec[i].getAsignatura());
                lstDatos.add("Promedio: "+ objVec.vec[i].getSuma());
                lstDatos.add("SUPLETORIO");
                lstDatos.add("*******************************************");
                conta ++;
            }else
                    if (objVec.vec[i].getSuma()<16) {
                lstDatos.add("Nombre: "+ objVec.vec[i].getNombres());
                lstDatos.add("Materia: "+ objVec.vec[i].getApellidos());
                lstDatos.add("Promedio: "+ objVec.vec[i].getSuma());
                lstDatos.add("REPROBADO");
                lstDatos.add("*******************************************");
                conta ++;
            }
            
            
        }
    }//GEN-LAST:event_btnEstadoActionPerformed
//clase alumno,nota;nombre asignatura y tres notas parciales de un curso de n estudiantes
//-clases
//-formularios
//-datos prueba
//-mostrar datos ordenado suma
//-estado a,s,p
//-el estuante con la suma mas alta
    public void limpiar() {
        txtCedula.setText(null);
        txtNombre.setText("");
        txtApellido.setText(null);
        txtAsignatura.setText(null);
        txtn1.setText(null);
        txtn2.setText(null);
        txtn3.setText(null);
                
        lstDatos.removeAll();
 
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnPrueba;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnordenar;
    private javax.swing.JComboBox<String> cboestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblaprobados;
    private java.awt.List lstDatos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAsignatura;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtn1;
    private javax.swing.JTextField txtn2;
    private javax.swing.JTextField txtn3;
    // End of variables declaration//GEN-END:variables
}
