package Formularios;

//importar las clases//
import Clases.Banco;
import Clases.Cliente;
import Clases.Cuenta;
import Clases.NumeroL;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//**************************//

public class frmCuentasCoac extends javax.swing.JFrame {

    /**
     * Creates new form frmEjerClientBanc
     */
    public frmCuentasCoac() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnPagar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelef = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNroCta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        cmbTipoCta = new javax.swing.JComboBox<>();
        lblFecha = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        rbtDeposito = new javax.swing.JRadioButton();
        rbtRetiro = new javax.swing.JRadioButton();
        lstDatos = new java.awt.List();
        txtValor = new javax.swing.JTextField();
        txtValorL = new javax.swing.JTextField();
        lblCheque = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spnNClientes = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        lstcuenta = new java.awt.List();
        jLabel12 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnCrearBanco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUENTAS DE COAC");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagar);
        btnPagar.setBounds(20, 430, 100, 40);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cedula :");

        txtCedula.setBackground(new java.awt.Color(204, 255, 204));
        txtCedula.setText("1003400973");
        txtCedula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre :");

        txtNombre.setBackground(new java.awt.Color(204, 255, 204));
        txtNombre.setText("José Perugachi");
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Direccion :");

        txtDireccion.setBackground(new java.awt.Color(204, 255, 204));
        txtDireccion.setText("Otavalo");
        txtDireccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Telefono :");

        txtTelef.setBackground(new java.awt.Color(204, 255, 204));
        txtTelef.setText("0985934027");
        txtTelef.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDireccion))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtTelef))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedula)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelef, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCedula, txtDireccion, txtNombre, txtTelef});

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 260, 230);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE CUENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nro cuenta :");

        txtNroCta.setBackground(new java.awt.Color(204, 255, 204));
        txtNroCta.setText("6785");
        txtNroCta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fecha Apertura :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Tipo :");

        btnCrear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        cmbTipoCta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbTipoCta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahorro", "Credito", "Corriente" }));

        lblFecha.setBackground(new java.awt.Color(204, 255, 204));
        lblFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFecha.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipoCta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroCta, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblFecha, txtNroCta});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroCta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbTipoCta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblFecha, txtNroCta});

        jPanel1.add(jPanel3);
        jPanel3.setBounds(280, 0, 271, 230);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRANSACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Cantidad:");

        txtCantidad.setBackground(new java.awt.Color(204, 255, 204));
        txtCantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });

        buttonGroup1.add(rbtDeposito);
        rbtDeposito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtDeposito.setText("Deposito");

        buttonGroup1.add(rbtRetiro);
        rbtRetiro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtRetiro.setText("Retiro");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(rbtDeposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(rbtRetiro)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtDeposito)
                    .addComponent(rbtRetiro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCantidad)
                        .addGap(1, 1, 1)))
                .addGap(24, 24, 24)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 240, 250, 150);

        lstDatos.setBackground(new java.awt.Color(204, 255, 204));
        lstDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstDatosActionPerformed(evt);
            }
        });
        jPanel1.add(lstDatos);
        lstDatos.setBounds(290, 240, 260, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 30, 560, 389);
        getContentPane().add(txtValor);
        txtValor.setBounds(390, 480, 150, 30);
        getContentPane().add(txtValorL);
        txtValorL.setBounds(60, 520, 470, 30);

        lblCheque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CHEQUE3 001.jpg"))); // NOI18N
        getContentPane().add(lblCheque);
        lblCheque.setBounds(10, 430, 560, 207);

        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Número Max. de Clientes:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(600, 60, 120, 40);
        getContentPane().add(spnNClientes);
        spnNClientes.setBounds(730, 60, 50, 30);

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Transacciones"));

        lstcuenta.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setText("Ingrese el Nro de cuenta : ");

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lstcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(586, 140, 300, 270);

        btnCrearBanco.setText("Crear Banco");
        btnCrearBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearBancoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearBanco);
        btnCrearBanco.setBounds(800, 60, 91, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * *********************************************************************************************
     * // INSTITUTO TECNOLOGICO SUPERIOR IBARRA // CARRERA: TECNOLOGIA EN
     * SISTEMAS //NOMBRE: Pillajo Antonio //NIVEL: Primero Sistemas
     * //FECHA:16/10/2018 //PROFESOR: Ing.Rene Pilataxi A //OBJETIVO: Crear 2
     * clases : // 1 clase llamada cliente // 1 clase llamada cuenta // de los
     * clientes se registra : // * cedula,nombre,direccion,telefono //
     * informacion de las cuentas de cliente contiene: // * Nro cuenta,fecha
     * apertura,tipo de cuenta,saldo // realizar los procesos para registrar los
     * depositos y retiros // de dicha cuenta (mantener actualizado el saldo) //
     * Al momento de crear la cuenta inicia con un saldo de $ 50 // Validar en
     * cuanto a retiros ya que el minimo valor de la cuenta // debe estar $ 10
     //*****************************************************************************************
     */
    //llama la clase cliente//
    Cliente objCli;
    //llama la clase cuenta//
    Cuenta objCuenta;

    //funcion para mostrar la fecha del sistema//
    public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    private void lstDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstDatosActionPerformed

    //funcion para mostrar los datos ingresados//
//    public void mostrarDatos() {
//
//        lstDatos.removeAll();
//        lstDatos.add("****DATOS GENERAL****");
//        lstDatos.add("Nro. Cta:" + objCuenta.getNroCuenta());
//        lstDatos.add("Nombre:" + objCli.getNombre());
//        lstDatos.add("Dirección:" + objCli.getDireccion());
//        lstDatos.add("Fecha apertura :" + objCuenta.getFechaAbre());
//        lstDatos.add("Saldo :" + objCuenta.getSaldo());
//    }
    
      public void mostrarDatos() {
        lstDatos.removeAll();
        for (int i = 0; i < objBanco.getTam(); i++) {

            lstDatos.add("Nro. Cta : " + objBanco.vecCta[i].getNroCuenta());
            lstDatos.add("Nombre : " + objBanco.vecCta[i].getCliente().getNombre());
            lstDatos.add("Dirección :" + objBanco.vecCta[i].getCliente().getDireccion());
            lstDatos.add("Saldo : " + objBanco.vecCta[i].getSaldo());
            lstDatos.add("------------------------------------");
        }
    }
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        //ingresando datos en cliente//
//        if(objBanco.getTam()>=nClientes){
//              JOptionPane.showMessageDialog(this, "Banco Lleno Papu..!!");
//        }else{
//        String ced = txtCedula.getText();
//        String nom = txtNombre.getText();
//        String dir = txtDireccion.getText();
//        String tlf = txtTelef.getText();
//        //crear al cliente con los datos//
//        objCli = new Cliente(ced, nom, dir, tlf);
//
//        //ingresado datos en cuenta//
//        int nroCta = Integer.parseInt(txtNroCta.getText());
//        String tipo = cmbTipoCta.getSelectedItem().toString();
//        //crear cuenta con los datos//
//        objCuenta = new Cuenta(nroCta/*envia cuenta*/,
//                objCli/*envia cliente*/,
//                lblFecha.getText()/*envia fecha*/,
//                tipo/*envia tipo cuenta*/);
//        mostrarDatos();//llama la funcion mostrar para que muetre los datos
//        JOptionPane.showMessageDialog(this, "Cuenta creada con Exito..!!");
//        }
 if (objBanco.getTam() >= nClientes) {
            JOptionPane.showMessageDialog(this, "VECTOR LLENO");
        } else {
            String ced = txtCedula.getText();
            String nom = txtNombre.getText();
            String dir = txtDireccion.getText();
            String tlf = txtTelef.getText();
            Cliente objCli = new Cliente(ced, nom, dir, tlf);
            int nroCta = Integer.parseInt(txtNroCta.getText());
            String tipo;
            tipo = cmbTipoCta.getSelectedItem().toString();
            Cuenta objCuenta = new Cuenta(nroCta, objCli, lblFecha.getText(), tipo);
            objBanco.agregaCuenta(objCuenta);
            limpiar();
            mostrarDatos();
            JOptionPane.showMessageDialog(this, "a con Exito..!!");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //llama la funcion de fecha para mostrar en el formulario//
//        ImageIcon Verdad = new ImageIcon(getClass().getResource("/Imagenes/asdad.jpg"));
//        ImageIcon icono = new ImageIcon(Verdad.getImage().getScaledInstance(lblInagensita.getWidth(), lblInagensita.getHeight(), Image.SCALE_DEFAULT));
//        lblInagensita.setIcon(icono);
        lblFecha.setText(fechaactual());
    }//GEN-LAST:event_formWindowOpened

     public void limpiar() {
        txtCedula.setText(null);
        txtNombre.setText("");
        txtDireccion.setText(null);
        txtTelef.setText(null);
        txtNroCta.setText(null);
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
       double cantidad = Double.parseDouble(txtCantidad.getText());
        if (rbtDeposito.isSelected()) {
            objBanco.vecCta[pos].depositar(cantidad);
        }
        if (rbtRetiro.isSelected()) {
            if (objBanco.vecCta[pos].getSaldo() > 10) {
                objBanco.vecCta[pos].retirar(cantidad);
            } else {
                JOptionPane.showMessageDialog(this, "SALDO INSUFICIENTE");
            }

        }
        lstDatos.removeAll();
        mostrarDatos();
        lstcuenta.removeAll();
        mostrarDatos2();

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        // TODO add your handling code here:
//        if (objCuenta.saldo-cantidad <=10) {
//            JOptionPane.showMessageDialog(this, "minimo 10");
//           // btnRegistrar.setEnabled(false);
//            objCuenta.depositar(cantidad);
//            mostrarDatos();
//        }
    }//GEN-LAST:event_txtCantidadFocusLost

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:

        txtValorL.setText(NumeroL.cantidadConLetra(txtValor.getText()));
        
        double cantidad;
        cantidad = Double.parseDouble(txtValor.getText());
// 
           objBanco.vecCta[pos].retirar(cantidad);
          lstcuenta.removeAll();
            mostrarDatos2();
//          

        mostrarDatos();

    }//GEN-LAST:event_btnPagarActionPerformed
   int nClientes;
    Banco objBanco;
    private void btnCrearBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearBancoActionPerformed
        // TODO add your handling code here:
        nClientes = Integer.parseInt(spnNClientes.getValue().toString());
        objBanco = new Banco(nClientes);
        btnCrearBanco.setEnabled(false);
        btnCrear.setEnabled(true);
    }//GEN-LAST:event_btnCrearBancoActionPerformed
int pos=0;
 public void mostrarDatos2() {
        lstcuenta.add("Nro. Cta : " + objBanco.vecCta[pos].getNroCuenta());
        lstcuenta.add("Nombre : " + objBanco.vecCta[pos].getCliente().getNombre());
        lstcuenta.add("Dirección : " + objBanco.vecCta[pos].getCliente().getDireccion());
        lstcuenta.add("Saldo : " + objBanco.vecCta[pos].getSaldo());
        // lstDatos.add("Saldo :" + 

    }
    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        lstcuenta.removeAll();
        int in = 0;
        btnRegistrar.setEnabled(false);
        int id = Integer.parseInt(txtbuscar.getText());
        for (int i = 0; i < objBanco.getTam(); i++) {
            if (objBanco.vecCta[i].getNroCuenta() == id) {
                pos = i;
                in++;
                mostrarDatos2();
                btnRegistrar.setEnabled(true);
            }
        }
        if (in == 0) {
            JOptionPane.showMessageDialog(null, "Cuenta no encontrada");

        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuentasCoac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuentasCoac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuentasCoac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuentasCoac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCuentasCoac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCrearBanco;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbTipoCta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCheque;
    private javax.swing.JLabel lblFecha;
    private java.awt.List lstDatos;
    private java.awt.List lstcuenta;
    private javax.swing.JRadioButton rbtDeposito;
    private javax.swing.JRadioButton rbtRetiro;
    private javax.swing.JSpinner spnNClientes;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNroCta;
    private javax.swing.JTextField txtTelef;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorL;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
